# Generated by Django 3.1.5 on 2021-01-30 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasources', '0002_auto_20210130_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasources.datasource')),
            ],
        ),
    ]
