# Generated by Django 3.1.5 on 2021-01-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_comment_submission_subreddit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
