# Generated by Django 3.1.5 on 2021-01-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20210130_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='text',
            field=models.CharField(max_length=5000),
        ),
    ]
