# Generated by Django 3.1.5 on 2021-01-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20201229_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='Instant Report', max_length=100),
        ),
    ]
