# Generated by Django 3.1.5 on 2021-02-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20210130_2356'),
        ('reports', '0004_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(default='Started', max_length=50),
        ),
        migrations.CreateModel(
            name='SubmissionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_polarity', models.FloatField(default=0.0)),
                ('title_subjectivity', models.FloatField(default=0.0)),
                ('title_sentiment', models.CharField(default='Neutral', max_length=20)),
                ('text_polarity', models.FloatField(default=0.0)),
                ('text_subjectivity', models.FloatField(default=0.0)),
                ('text_sentiment', models.CharField(default='Neutral', max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.submission')),
            ],
        ),
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordcloud_image_b64', models.CharField(max_length=100000)),
                ('word_count', models.JSONField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_polarity', models.FloatField(default=0.0)),
                ('body_subjectivity', models.FloatField(default=0.0)),
                ('body_sentiment', models.CharField(default='Neutral', max_length=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.comment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
        ),
    ]
