# Generated by Django 3.1.5 on 2021-02-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20210201_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdetail',
            name='negative_comment_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportdetail',
            name='negative_submission_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportdetail',
            name='positive_comment_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportdetail',
            name='positive_submission_score',
            field=models.IntegerField(default=0),
        ),
    ]
