# Generated by Django 3.1.6 on 2021-02-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20210202_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdetail',
            name='graph_image_b64',
            field=models.CharField(max_length=200000, null=True),
        ),
    ]
