# Generated by Django 3.1.6 on 2021-02-02 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20210202_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('probability', models.FloatField(default=0.0)),
                ('uri', models.CharField(max_length=1000)),
                ('entity_id', models.CharField(max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
        ),
    ]
