# Generated by Django 3.1.6 on 2021-02-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_reportentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdetail',
            name='graph_image_b64',
            field=models.CharField(max_length=300000, null=True),
        ),
    ]
