# Generated by Django 3.1.4 on 2020-12-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('reddit_id', models.CharField(max_length=500)),
                ('created_utc', models.DateTimeField()),
                ('score', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=500)),
                ('upvote_ratio', models.FloatField(default=0.0)),
            ],
        ),
    ]
