# Generated by Django 3.1.5 on 2021-02-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_auto_20210130_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='weight',
        ),
        migrations.AddField(
            model_name='datasource',
            name='limit',
            field=models.IntegerField(default=100),
        ),
    ]
