# Generated by Django 3.1.5 on 2021-01-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='polarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='subjectivity',
            field=models.FloatField(default=0.0),
        ),
    ]
