# Generated by Django 3.1.5 on 2021-01-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_auto_20210112_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='annotations',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='mentions',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
