# Generated by Django 3.1.5 on 2021-01-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_auto_20210112_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreddit',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='subreddit',
            name='mentions',
        ),
    ]
