# Generated by Django 3.1.5 on 2021-01-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_auto_20210112_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
